### ISSUE TITLE
Thoughts about splink_graph API/UX

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink_graph#22]
**Consistency in naming**

There should be common names for different 'things' across API calls.  We can decide what the names should be but for example:

- Subgraphs (clusters)
- Nodes (components)
- Edges  (pairwise record comparison)

And these should filter through to everything

For example:
```
from splink_graph.cluster_metrics import x
from splink_graph.node_metrics import x
from splink_graph.edge_metrics import x
```

The in functions we want consistency in what things are called:

cluster_metrics should expect a cluster_id 
node_metrics should expect node_id 
edge metrics should expect src dst

We should always use these when performing joins.  So for example:

```
df_nodes = cc.withColumnRenamed("id","index").withColumnRenamed("component","group")

df_nodes = df_nodes.withColumn("name",f.col("index"))
node_df_for_viz = df_nodes.join(node_eigen_centrality,(df_nodes.index==node_eigen_centrality.node)).drop("node")
node_df_for_viz.show(2)
```
relies on the index of a dataframe.  But we should join on the node_id

Method calls could be like:

```
from splink_graph.node_metrics import eigencentrality
node_eigen_centrality = eigencentrality(edge_df )


```

where the default arguments for `eigencentrality` are the default names:

```
cluster_id_colname="cluster_id", distance_colname="distance",
               src_colname="src", dst="dst"
```

**Comment by mamonu** [comment]
all suggestions implemented. Closing
