### ISSUE TITLE
Division by zero error within NetworkX `cluster_eb_modularity`

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink_graph#49]
```
File "/home/spark/.local/lib/python3.7/site-packages/splink_graph/cluster_metrics.py", line 359, in cluster_eb_m
    co_eb_mod = nx_comm.modularity(nxGraph, gn)
  File "/home/spark/.local/lib/python3.7/site-packages/networkx/algorithms/community/quality.py", line 342, in modularity
    norm = 1 / deg_sum ** 2
ZeroDivisionError: float division by zero
```

I will try and delve a little deeper into the cause of this...

**Comment by mamonu** [comment]
a graph with no degrees/degree 0 ie one node by itself would have a degree sum of 0 hence... div by zero.

I need to be more defensive about situations like that.... like if nodecount is less than 2 we dont need any advanced metrics a default will do...

**Comment by mamonu** [comment]
can you test if  it still fails on the data you have?

**Comment by mamonu** [comment]
also is it possible to have the subgraph/network that caused this? it would be interesting to have as a test case

**Comment by RobinL** [comment]
I edited the `cluster_eb_modularity` function to include:

```
co = pdf[cluster_id_colname].iloc[0]  # access component id
        try:
            co_eb_mod = nx_comm.modularity(nxGraph, gn)
        except ZeroDivisionError:
            raise Exception(f"ZeroDivisionError on component id {co}")
```

Which gave me the following component:

| src        | dst        |   weight |   cluster_id |
|:-----------|:-----------|---------:|-------------:|
| Q1699654-1 | Q1699654-2 |        0 |  51539607590 |

**Comment by RobinL** [comment]
The problem is weight=0 rather than cluster size=1.

This works
```
from pyspark.sql import Row
data_list = [{"src": "a", "dst": "b", "weight": 0.1, "cluster_id": 1}]
df = spark.createDataFrame(Row(**x) for x in data_list)
cluster_eb_modularity(df, distance_colname="weight").toPandas()
```

This fails:

```
from pyspark.sql import Row
data_list = [{"src": "a", "dst": "b", "weight": 0.0, "cluster_id": 1}]
df = spark.createDataFrame(Row(**x) for x in data_list)
cluster_eb_modularity(df, distance_colname="weight").toPandas()
```

**Comment by RobinL** [comment]
Can confirm my big job (on 100k clusters) works so long as there are no weight=0 edges.  I'll do a PR
