### ISSUE TITLE
Implement `has_bridges` as a cluster metric

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink_graph#53]
In addition to the edge function that gives us  `bridges`,  it'd be useful to classify clusters as to whether they have bridges

We should be able to use `networkX`'s `has_bridges` for this.

I'll have a crack at implementing this

**Comment by RobinL** [comment]
Thinking about this, `num_bridges` may be preferable.  More information and easy to convert into `has_bridges` if required

**Comment by mamonu** [comment]
I thought about this and in demo notebooks I was getting this  by doing a group_by and count() on `cluster_id` on
the result of bridge_edges ?


of course this ⏫ would be missing the cluster_ids that are not bridges
